version: '3.4'

services:
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
            - ELASTIC_PASSWORD=elastic
            - ELASTIC_USER=elastic
            - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
    azurite:
        image: 	mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
            - "10001:10001"
            - "10002:10002"
volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge

